### ISSUE TITLE
Most features don't work with submodules

### ISSUE THREAD

**Issue by k8ieone** [pragtical/scm#1]
When using git submodules, the plugin doesn't show modified content in files correctly (changes are shown only until you save the file). The directory with the submodule shows as modified in the tree, but none of the files show up as modified. Blame also doesn't work.

**Comment by jgmdev** [comment]
Fixed on latest version, give it a try and let me know. Thanks for reporting!

**Comment by k8ieone** [comment]
Looks good, thanks!
